spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
  application.id: default

spring.cloud.stream.kafka.binder.headers: x-retries
spring.cloud.stream.kafka.binder.configuration.auto.offset.reset: earliest

server.port: 8081

spring.cloud.stream.bindings.testeReplay:
  destination: 1-teste-replay
  group: consumidorTesteReplay
  partitioned: true
  max-attempts: 4

spring.cloud.stream.kafka.bindings.testeReplay.consumer.enableDlq: true
spring.cloud.stream.kafka.bindings.testeReplay.consumer.dlqName: dlq-teste-3

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
  zkNodes: localhost
  serdeError: sendToDlq
