spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
  application.id: default

spring.cloud.stream.kafka.binder.headers: x-retries
spring.cloud.stream.kafka.binder.configuration.auto.offset.reset: earliest


spring.cloud.stream.bindings.teste:
  destination: 1-teste
  group: consumidorTeste
  partitioned: true
  max-attempts: 1

spring.cloud.stream.bindings.testeProdutor:
  destination: 1-teste

spring.cloud.stream.bindings.testeReplay:
  destination: 1-teste-replay

spring.cloud.stream.kafka.bindings.teste.consumer.enableDlq: true
spring.cloud.stream.kafka.bindings.teste.consumer.dlqName: dlq-teste-3

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
  zkNodes: localhost
  serdeError: sendToDlq
